server:
  port: 8080

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: event-service-public
          uri: lb://event-service
          predicates:
            - Path=/events/**,/compilations/**,/categories/**

        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: category-service-admin
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**

        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/comments/**,/admin/comments/**,/users/*/comments/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always